version: '3.5'
services:
  php:
    image: zaikron/aspichatappv2:latest
    restart: always
    ports:
      - 8000:80
    environment:
      - APP_KEY="base64:0Wp/6uq52p6TPi/YF5XPFKoRuoytN6EQccdcSZ65hds="
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
  mysql:
    image: zaikron/aspichatdb:latest
    restart: always
    environment:
      MYSQL_DATABASE: careersudg
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"