<?php
$careers = [
    'Licenciatura en Artes Audiovisuales' => 'Licenciatura en Artes Audiovisuales(Artes Escénicas y Visuales)',
    'Licenciatura en Artes Escénicas' => 'Licenciatura en Artes Escénicas(Artes Escénicas y Visuales)',
    'Licenciatura en Artes Visuales' => 'Licenciatura en Artes Visuales(Artes Escénicas y Visuales)',
    'Licenciatura en Diseño de Interiores y Ambientación' => 'Licenciatura en Diseño de Interiores y Ambientación(Diseño y Creatividad)',
    'Licenciatura en Diseño de Modas' => 'Licenciatura en Diseño de Modas(Diseño y Creatividad)',
    'Licenciatura en Diseño Industrial' => 'Licenciatura en Diseño Industrial(Diseño y Creatividad)',
    'Licenciatura en Diseño para la Comunicación Gráfica' => 'Licenciatura en Diseño para la Comunicación Gráfica(Diseño y Creatividad)',
    'Licenciatura en Diseño de Artesanías' => 'Licenciatura en Diseño de Artesanías(Diseño y Creatividad)',
    'Licenciatura en Medicina Veterinaria y Zootecnia' => 'Licenciatura en Medicina Veterinaria y Zootecnia(Ciencias de la Salud)',
    'Médico Cirujano y Partero' => 'Médico Cirujano y Partero(Ciencias de la Salud)',
    'Licenciatura en Cirujano Dentista' => 'Licenciatura en Cirujano Dentista(Ciencias de la Salud)',
    'Enfermería' => 'Enfermería(Ciencias de la Salud)',
    'Licenciatura en Nutrición' => 'Licenciatura en Nutrición(Ciencias de la Salud)',
    'Licenciatura en Psicología' => 'Licenciatura en Psicología(Ciencias de la Salud)',
    'Licenciatura en Antropología' => 'Licenciatura en Antropología(Ciencias Sociales y Humanidades)',
    'Licenciatura en Historia' => 'Licenciatura en Historia(Ciencias Sociales y Humanidades)',
    'Licenciatura en Letras Hispánicas' => 'Licenciatura en Letras Hispánicas(Ciencias Sociales y Humanidades)',
    'Licenciatura en Relaciones Internacionales' => 'Licenciatura en Relaciones Internacionales(Ciencias Sociales y Humanidades)',
    'Licenciatura en Sociología' => 'Licenciatura en Sociología(Ciencias Sociales y Humanidades)',
    'Licenciatura en Trabajo Social' => 'Licenciatura en Trabajo Social(Ciencias Sociales y Humanidades)',
    'Licenciatura en Ingeniero Agrónomo' => 'Licenciatura en Ingeniero Agrónomo(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería Biomédica' => 'Licenciatura en Ingeniería Biomédica(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería Civil' => 'Licenciatura en Ingeniería Civil(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería en Computación' => 'Licenciatura en Ingeniería en Computación(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería Industrial' => 'Licenciatura en Ingeniería Industrial(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería Mecánica Eléctrica' => 'Licenciatura en Ingeniería Mecánica Eléctrica(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería Química' => 'Licenciatura en Ingeniería Química(Ingenierías y Tecnologías)',
    'Licenciatura en Ingeniería Topográfica' => 'Licenciatura en Ingeniería Topográfica(Ingenierías y Tecnologías)',
    'Ingeniería en Videojuegos' => 'Ingeniería en Videojuegos(Ingenierías y Tecnologías)',
    'Licenciatura en Administración' => 'Licenciatura en Administración(Administración y Negocios)',
    'Licenciatura en Negocios Internacionales' => 'Licenciatura en Negocios Internacionales(Administración y Negocios)',
    'Licenciatura en Recursos Humanos' => 'Licenciatura en Recursos Humanos(Administración y Negocios)',
    'Licenciatura en Mercadotecnia' => 'Licenciatura en Mercadotecnia(Administración y Negocios)',
    'Licenciatura en Biología' => 'Licenciatura en Biología(Ciencias Formales Naturales y Ambientales)',
    'Licenciatura en Ciencia de los Alimentos' => 'Licenciatura en Ciencia de los Alimentos(Ciencias Formales Naturales y Ambientales)',
    'Licenciatura en Física' => 'Licenciatura en Física(Ciencias Formales Naturales y Ambientales)',
    'Licenciatura en Matemáticas' => 'Licenciatura en Matemáticas(Ciencias Formales Naturales y Ambientales)',
    'Licenciatura en Química' => 'Licenciatura en Química(Ciencias Formales Naturales y Ambientales)',
    'Licenciatura en Comunicación Pública' => 'Licenciatura en Comunicación Pública(Comunicación y Periodismo)',
    'Licenciatura en Periodismo' => 'Licenciatura en Periodismo(Comunicación y Periodismo)',
    'Licenciatura en Lengua Extranjera' => 'Licenciatura en Lengua Extranjera(Educación y Pedagogía)',
    'Licenciatura en Estudios Políticos y Gobierno' => 'Licenciatura en Estudios Políticos y Gobierno(Educación y Pedagogía)',
    'Licenciatura en Filosofía' => 'Licenciatura en Filosofía(Educación y Pedagogía)',
    'Licenciatura en Pedagogía' => 'Licenciatura en Pedagogía(Educación y Pedagogía)',
    'Licenciatura en Educación' => 'Licenciatura en Educación(Educación y Pedagogía)',
    'Licenciatura en Turismo' => 'Licenciatura en Turismo(Turismo y Cultura)',
    'Licenciatura en Cultura Física y Deportes' => 'Licenciatura en Cultura Física y Deportes(Turismo y Cultura)',
    'Licenciatura en Gestión Cultural' => 'Licenciatura en Gestión Cultural(Turismo y Cultura)',
    'Licenciatura en Desarrollo Turístico Sustentable' => 'Licenciatura en Desarrollo Turístico Sustentable(Turismo y Cultura)'
];


$areas = [
    'Artes Escénicas y Visuales' => 'Artes Escénicas y Visuales',
    'Diseño y Creatividad' => 'Diseño y Creatividad',
    'Ciencias de la Salud' => 'Ciencias de la Salud',
    'Ciencias Sociales y Humanidades' => 'Ciencias Sociales y Humanidades',
    'Ingenierías y Tecnologías' => 'Ingenierías y Tecnologías',
    'Administración y Negocios' => 'Administración y Negocios',
    'Ciencias Formales Naturales y Ambientales' => 'Ciencias Formales Naturales y Ambientales',
    'Comunicación y Periodismo' => 'Comunicación y Periodismo',
    'Educación y Pedagogía' => 'Educación y Pedagogía',
    'Turismo y Cultura' => 'Turismo y Cultura'
];

?>